#!/bin/bash

python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_kaiming.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8881_legacycomplex_kaiming --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8881 --wandb_group speechcommands --wandb_tags "kaiming"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_xavier.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8881_legacycomplex_xavier --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8881 --wandb_group speechcommands --wandb_tags "xavier"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_random.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8881_legacycomplex_random --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8881 --wandb_group speechcommands --wandb_tags "random"

python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_kaiming.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8882_legacycomplex_kaiming --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8882 --wandb_group speechcommands --wandb_tags "kaiming"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_xavier.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8882_legacycomplex_xavier --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8882 --wandb_group speechcommands --wandb_tags "xavier"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_random.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8882_legacycomplex_random --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8882 --wandb_group speechcommands --wandb_tags "random"

python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_kaiming.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8883_legacycomplex_kaiming --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8883 --wandb_group speechcommands --wandb_tags "kaiming"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_xavier.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8883_legacycomplex_xavier --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8883 --wandb_group speechcommands --wandb_tags "xavier"
python train_xla.py --cfg_file ./cfgs/speechcommands/efficientnet-b0-leaf-default_random.cfg -e ~/leaf_experiments/speechcommands/efficientnet-b0_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8883_legacycomplex_random --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8883 --wandb_group speechcommands --wandb_tags "random"

# python train_xla.py --cfg_file ./cfgs/speechcommands/resnet-18-leaf-default.cfg -e ~/leaf_experiments/speechcommands/resnet-18_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8881_legacycomplex --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8881 --wandb_group speechcommands
# python train_xla.py --cfg_file ./cfgs/speechcommands/resnet-18-leaf-default.cfg -e ~/leaf_experiments/speechcommands/resnet-18_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8882_legacycomplex --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8882 --wandb_group speechcommands
# python train_xla.py --cfg_file ./cfgs/speechcommands/resnet-18-leaf-default.cfg -e ~/leaf_experiments/speechcommands/resnet-18_default_leaf_bs1x256_adam_warmupcosine_wd_1e-4_rs8883_legacycomplex --epochs 100 --num_workers 4 --log_steps 50 --random_seed 8883 --wandb_group speechcommands
